### ISSUE TITLE
Reboot in recovery mode is breaking recovery

### ISSUE THREAD

**Issue by tanergergul** [SDM710-Development/android_device_xiaomi_pyxis#11]
When I select reboot in recovery mode from the power options , the device boots into fastboot mode and does not turn on again. It is breaking recovery. I was solved this by flashing recovery again.

**Comment by nE0sIghT** [comment]
I not confirming this.  
Reboot to recovery works for me

**Comment by uixdess** [comment]
Not confirmed issue.
Closed.
